export async function deployViewAggregator(ethers: any, { upgrades, CONTRACT_ADDRESS }: any) {
  const ViewAggregator = await ethers.getContractFactory("ViewAggregator")
  const viewAggregator = await upgrades.deployProxy(ViewAggregator, [
    CONTRACT_ADDRESS.OPTIONS_AUTHORITY,
    CONTRACT_ADDRESS.POSITION_MANAGER,
    CONTRACT_ADDRESS.VAULT_PRICE_FEED,
    [CONTRACT_ADDRESS.S_VAULT, CONTRACT_ADDRESS.M_VAULT, CONTRACT_ADDRESS.L_VAULT],
    [CONTRACT_ADDRESS.S_OLP, CONTRACT_ADDRESS.M_OLP, CONTRACT_ADDRESS.L_OLP],
    [CONTRACT_ADDRESS.S_OLP_MANAGER, CONTRACT_ADDRESS.M_OLP_MANAGER, CONTRACT_ADDRESS.L_OLP_MANAGER],
    [CONTRACT_ADDRESS.S_REWARD_DISTRIBUTOR, CONTRACT_ADDRESS.M_REWARD_DISTRIBUTOR, CONTRACT_ADDRESS.L_REWARD_DISTRIBUTOR],
    [CONTRACT_ADDRESS.S_VAULT_UTILS, CONTRACT_ADDRESS.M_VAULT_UTILS, CONTRACT_ADDRESS.L_VAULT_UTILS]
  ])

  CONTRACT_ADDRESS.VIEW_AGGREGATOR = await viewAggregator.getAddress()

  console.log(CONTRACT_ADDRESS, 'CONTRACT_ADDRESS')

  return { viewAggregator }
}